[package]
name = "marching_squares"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["dynamic"]
dynamic = ["bevy/dynamic"]

[dependencies]
bevy = { version = "0.6.0" }
rand = "0.8.4"
